<a href="https://colab.research.google.com/github/KimuraRyuji/repository/blob/main/%E6%A0%AA%E4%BE%A1%E5%8F%96%E5%BE%97%E3%82%A2%E3%83%97%E3%83%AA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install yfinance
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.2.4-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.4/51.4 KB 1.3 MB/s eta 0:00:00
Collecting frozendict>=2.3.4
  Downloading frozendict-2.3.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 KB 6.8 MB/s eta 0:00:00
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.8/dist-packages (from yfinance) (4.9.2)
Collecting beautifulsoup4>=4.11.1
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 KB 5.9 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (2022.7)
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 KB 9.1 MB/s eta 0:00:00
Collecting cryptography>=3.3.2
  Downloading cryptography-39.0.0-cp36-abi3-manylinux_2_24_x86_64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 80.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.21.6)
Collecting requests>=2.26
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 4.3 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.4.4)
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (1.15.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)
Installing collected packages: soupsieve, requests, html5lib, frozendict, cryptography, beautifulsoup4, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: html5lib
    Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Successfully installed beautifulsoup4-4.11.1 cryptography-39.0.0 frozendict-2.3.4 html5lib-1.1 requests-2.28.2 soupsieve-2.3.2.post1 yfinance-0.2.4

In [41]:
days = 20
tickers = {
    'apple': 'AAPL',
    'Meta': 'META',
    'MicroSoft': 'msft',
    'google': 'GOOGL',
    'Netflix': 'NFLX',
    'Amazon': 'AMZN'
}

def get_data(days, tickers):
    df = pd.DataFrame()
    for company in tickers.keys():
        tkr = yf.Ticker(tickers[company])
        hist = tkr.history(period=f'{days}d')
        hist.index = hist.index.strftime('%d %B %Y')
        hist = hist[['Close']]
        hist.columns = [company]
        hist = hist.T
        hist.index.name = 'NAME'
        df = pd.concat([df, hist])
    return df

In [42]:
days = 20
tickers = {
    'apple': 'AAPL',
    'Meta': 'META',
    'MicroSoft': 'msft',
    'google': 'GOOGL',
    'Netflix': 'NFLX',
    'Amazon': 'AMZN'
}

get_data(days, tickers)

Date,15 December 2022,16 December 2022,19 December 2022,20 December 2022,21 December 2022,22 December 2022,23 December 2022,27 December 2022,28 December 2022,29 December 2022,30 December 2022,03 January 2023,04 January 2023,05 January 2023,06 January 2023,09 January 2023,10 January 2023,11 January 2023,12 January 2023,13 January 2023
NAME,,,,,,,,,,,,,,,,,,,,
apple,136.500000,134.509995,132.369995,132.300003,135.449997,132.229996,131.860001,130.029999,126.040001,129.610001,129.929993,125.070000,126.360001,125.019997,129.619995,130.149994,130.729996,133.490005,133.410004,134.759995
Meta,116.150002,119.430000,114.480003,117.089996,119.760002,117.120003,118.040001,116.879997,115.620003,120.260002,120.339996,124.739998,127.370003,126.940002,130.020004,129.470001,132.990005,132.889999,136.710007,136.979996
MicroSoft,249.009995,244.690002,240.449997,241.800003,244.429993,238.190002,238.729996,236.960007,234.529999,241.009995,239.820007,239.580002,229.100006,222.309998,224.929993,227.119995,228.850006,235.770004,238.509995,239.229996
google,90.860001,90.260002,88.440002,89.019997,89.580002,87.760002,89.230003,87.389999,86.019997,88.449997,88.230003,89.120003,88.080002,86.199997,87.339996,88.019997,88.419998,91.519997,91.129997,92.120003
Netflix,290.410004,290.709991,288.299988,288.190002,297.959991,297.750000,294.959991,284.170013,276.880005,291.119995,294.880005,294.950012,309.410004,309.700012,315.549988,315.170013,327.540009,327.260010,330.130005,332.820007
Amazon,88.449997,87.860001,84.919998,85.190002,86.769997,83.790001,85.250000,83.040001,81.820000,84.180000,84.000000,85.820000,85.139999,83.120003,86.080002,87.360001,89.870003,95.089996,95.269997,98.120003